<?php

echo "<h1>";
if (isset($_GET["comentario"]))
    echo $_GET["comentario"];
echo "</h1>";
echo "<br>";
echo "<h1>";
if (isset($_GET["fallout1"]))
    echo $_GET["fallout1"];
echo "</h1>";
echo "<br>";
echo "<h1>";
if (isset($_GET["fallout2"]))
    echo $_GET["fallout2"];
echo "</h1>";
echo "<br>";
echo "<h1>";
if (isset($_GET["favori1"]))
    echo $_GET["favori1"];
echo "</h1>";
echo "<br>";
echo "<h1>";
if (isset($_GET["email"]))
    echo $_GET["email"];
echo "</h1>";
echo "<br>";
echo "<h1>";
if (isset($_GET["contra"]))
    echo $_GET["contra"];
echo "</h1>";
echo "<br>";